apiVersion: v1
kind: Config
preferences: {}

# Define the cluster
clusters:
- cluster:
  # PLACE CERTIFICATE HERE
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXhOVEU1TWpJeU1sb1hEVEk1TVRBeE1qRTVNakl5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkJxClg4RVhaMGJEcTN0N0lnSmxWTXRCT05PK3ZoNm03V01yNUNjd1BQeDl1NmFUQ2tyVUpRdGNZdEphZzdxTTE2aWcKMDRMZUVZQmtqRUphYnpFTkdIdjNrS1hlNGJuaEdjOHNET1dxeFFqVmlhL2l6OEI0RWwrM0p2OGRlMTdEay9reQpBb0JMTy9Ma2tKdjZWSHI5V2xQQklzNUl5TFlyZjdCaS93WVhYOUlldVNVZ0tlTjN4YytHMkRvQ1h5TkdzVVhRClhNWE1pSFBQdEpwYUVUYWUzNmlCWnVXN0hEZG5wQVBBUGdiQVUrN0thRzY5T05INFNZcmNPQmRPYm5QYVRTdWwKQkY2QWdnbW9aR3pER0JUMVNmc1ZzNzhpQnBESzhEMUIzWDdrQk1wcHBtUVlGZzd0ZnhJZG01MFRKUWJ4OGVCVwptSDIzRnBEU0hFcy9QaEJTd1lrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHeE9mckc0NStWbmVCUFArall3ZGhXK1ZGb3QKRU9CelhYaWh0R3hQVm8yUlpsL2J2NXBFcjVZcHBjQmNFaDI0K3l2cnJ5Wk1lemhFM3k2UTU3OVJva0VQYm9Rawo4VEpsM0pmYjBUcHpQSzBKbXArNzVpQUFYOTVtMEFQUGx3clNkVnlmVG55QjBsZnJ5NjRhS2FtMEk0d2VSR2JaClZXcWg5VnZhaXlRRDhYTlBaVTUwZkVCOFpMRTFIYTlOZGo3MSt4WENIeGJtTmt1L1k0SGFId3psYmxxcTV0bnIKUUM4NGFnMm1vc2dsYXkwR1Jic0E1N1BKWmVNQ3lGTWdWUnB0L0VER1NOemhrZm8yOERqWHcxOFh5WEtOajRmRwpRSlNWbS83K0ZFSGNoSHFENER1NjMxR0tNa0NnRy9zdjJMNm1ia1pDNUtxdzlPeDdGRTlKSVBVR2FOTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    # You'll need the API endpoint of your Cluster here:
    server: https://9A1114C51953FDEDEB1851B588463DC8.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:111588580784:cluster/MIInternal-EKSCluster-PRD

  # Define the user
users:
- name: research-team-sa
  user:
    as-user-extra: {}
     # PLACE CERTIFICATE HERE
    client-key-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXhOVEU1TWpJeU1sb1hEVEk1TVRBeE1qRTVNakl5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkJxClg4RVhaMGJEcTN0N0lnSmxWTXRCT05PK3ZoNm03V01yNUNjd1BQeDl1NmFUQ2tyVUpRdGNZdEphZzdxTTE2aWcKMDRMZUVZQmtqRUphYnpFTkdIdjNrS1hlNGJuaEdjOHNET1dxeFFqVmlhL2l6OEI0RWwrM0p2OGRlMTdEay9reQpBb0JMTy9Ma2tKdjZWSHI5V2xQQklzNUl5TFlyZjdCaS93WVhYOUlldVNVZ0tlTjN4YytHMkRvQ1h5TkdzVVhRClhNWE1pSFBQdEpwYUVUYWUzNmlCWnVXN0hEZG5wQVBBUGdiQVUrN0thRzY5T05INFNZcmNPQmRPYm5QYVRTdWwKQkY2QWdnbW9aR3pER0JUMVNmc1ZzNzhpQnBESzhEMUIzWDdrQk1wcHBtUVlGZzd0ZnhJZG01MFRKUWJ4OGVCVwptSDIzRnBEU0hFcy9QaEJTd1lrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHeE9mckc0NStWbmVCUFArall3ZGhXK1ZGb3QKRU9CelhYaWh0R3hQVm8yUlpsL2J2NXBFcjVZcHBjQmNFaDI0K3l2cnJ5Wk1lemhFM3k2UTU3OVJva0VQYm9Rawo4VEpsM0pmYjBUcHpQSzBKbXArNzVpQUFYOTVtMEFQUGx3clNkVnlmVG55QjBsZnJ5NjRhS2FtMEk0d2VSR2JaClZXcWg5VnZhaXlRRDhYTlBaVTUwZkVCOFpMRTFIYTlOZGo3MSt4WENIeGJtTmt1L1k0SGFId3psYmxxcTV0bnIKUUM4NGFnMm1vc2dsYXkwR1Jic0E1N1BKWmVNQ3lGTWdWUnB0L0VER1NOemhrZm8yOERqWHcxOFh5WEtOajRmRwpRSlNWbS83K0ZFSGNoSHFENER1NjMxR0tNa0NnRy9zdjJMNm1ia1pDNUtxdzlPeDdGRTlKSVBVR2FOTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
   ## PLACE USER TOKEN HERE
    token: REDACTED

# Define the context: linking a user to a cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:111588580784:cluster/MIInternal-EKSCluster-PRD
    namespace: research-indexer-services-ns
    user: research-team-sa
  name: arn:aws:eks:us-east-1:111588580784:cluster/MIInternal-EKSCluster-PRD

  # Define current context
current-context: arn:aws:eks:us-east-1:111588580784:cluster/MIInternal-EKSCluster-PRD
